
server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://bleryjfudpixdj:8d85fa0ff3869685940939fa2437c0396a1180e8e01ff39c59421cdc7918eb3d@ec2-54-158-232-223.compute-1.amazonaws.com:5432/dfqfm74eu1d3ri
    username: bleryjfudpixdj
    password: 8d85fa0ff3869685940939fa2437c0396a1180e8e01ff39c59421cdc7918eb3d
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0